let FirebaseKeys = {
  APP_NAME: "Checkin",
  FIREBASE_API_KEY: "<YOUR_FIREBASE_API_KEY>",
  AUTH_DOMAIN: "<YOUR_FIREBASE_AUTH_DOMAIN>",
  DATABASE_URL: "<YOUR_FIREBASE_DATABASE_URL>",
  STORAGE_BUCKET: "<YOUR_FIREBASE_STORAGE_BUCKET>",
  MESSAGING_SENDER_ID: "<YOUR_FIREBASE_MESSAGING_SENDER_ID>",
};

export default FirebaseKeys;